name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter: [stable]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter }}

      - name: Get dependencies for rocket_chat_embeddedchat_component
        run: flutter pub get
        working-directory: packages/rocket_chat_embeddedchat_component

      - name: Get dependencies for rocket_chat_embeddedchat_component sample_app
        run: flutter pub get
        working-directory: packages/rocket_chat_embeddedchat_component/sample_app

      - name: Get dependencies for rocket_chat_api sample_app
        run: flutter pub get
        working-directory: packages/rocket_chat_api/sample_app

      - name: Get dependencies for rocket_chat_api
        run: flutter pub get
        working-directory: packages/rocket_chat_api

      - name: Run tests for rocket_chat_embeddedchat_component
        run: flutter test
        working-directory: packages/rocket_chat_embeddedchat_component

      - name: Run tests for rocket_chat_api
        run: flutter test
        working-directory: packages/rocket_chat_api

      - name: Analyze code for rocket_chat_embeddedchat_component
        run: flutter analyze
        working-directory: packages/rocket_chat_embeddedchat_component

      - name: Analyze code for rocket_chat_api
        run: flutter analyze
        working-directory: packages/rocket_chat_api

      - name: Compile rocket_chat_embeddedchat_component
        run: flutter pub publish --dry-run
        working-directory: packages/rocket_chat_embeddedchat_component

      - name: Compile rocket_chat_api
        run: flutter pub publish --dry-run
        working-directory: packages/rocket_chat_api

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: packages/*/artifacts
